### ISSUE TITLE
dynamic shape

### ISSUE THREAD

**Issue by okideal** [spacewalk01/nanosam-cpp#1]
nice work!

Does this project support the batch inference for decoder part?

**Comment by spacewalk01** [comment]
Thanks, currently not, but it could support by adding batching functions.

**Comment by okideal** [comment]
Got it, thanks. 
btw. Does the official repo release the onnx file with dynamic batch? or I could just use the released one to generate the engine with dynamic batch?

**Comment by spacewalk01** [comment]
In official one, only the input of points is dynamic while batch is static (batch size = 1). It is because the model can take left-top and right bottom-points for masking a bounding box or can take a single point for inference. You may look at export code in official repo to change static batch size to dynamic batch size.
